services:
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://langflow:langflow@postgres:5432/langflow
      - LANGFLOW_AUTO_LOGIN=true
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - langflow_network

  postgres:
    image: postgres:15-alpine
    container_name: langflow_postgres
    environment:
      - POSTGRES_USER=langflow
      - POSTGRES_PASSWORD=langflow
      - POSTGRES_DB=langflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - langflow_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U langflow"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  langflow_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
